name: on_express
description: A new Flutter project.
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  curved_navigation_bar: ^1.0.3
  dio: ^5.3.4
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.10
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  gap: ^3.0.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl:
  mime: ^1.0.4
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  toastification: ^1.1.0
  url_launcher: ^6.2.1
  uuid: ^4.2.1
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  conditional_builder_null_safety: ^0.0.6
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  geocoding: ^2.0.2
  geolocator: ^9.0.2
  flutter_html: ^3.0.0-beta.2
  flutter_polyline_points: ^2.0.0
  firebase_remote_config: ^4.3.8
  internet_connection_checker: ^1.0.0+1
  new_version_plus: ^0.0.11
  pretty_dio_logger: ^1.3.1
  auto_size_text: ^3.0.0
  dartz: ^0.10.1
  flutter_paypal_payment: ^1.0.6
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  flutter_credit_card: ^4.0.1
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/0.75x/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/translations/
    - assets/messages/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900